import bpy
from math import radians, pi
from bpy_lib import *

delete_all()

# object name: toilet
# part_1: stand
create_curve(name=['loop_1_1', 'loop_2_1'], control_points=[[[-0.102, -0.503, 0.244], [0.001, -0.503, 0.244], [0.105, -0.503, 0.244], [0.136, -0.503, 0.129], [0.136, -0.503, 0.022], [0.136, -0.503, -0.052], [0.08, -0.503, -0.109], [0.001, -0.503, -0.109], [-0.078, -0.503, -0.109], [-0.136, -0.503, -0.052], [-0.136, -0.503, 0.022], [-0.136, -0.503, 0.129]], [[-0.085, -0.331, 0.187], [0.001, -0.331, 0.187], [0.087, -0.331, 0.187], [0.127, -0.314, 0.129], [0.127, -0.314, 0.022], [0.127, -0.314, -0.052], [0.076, -0.314, -0.104], [0.001, -0.314, -0.104], [-0.074, -0.314, -0.104], [-0.127, -0.314, -0.052], [-0.127, -0.314, 0.022], [-0.127, -0.314, 0.129]]], handle_type=[3, 3, 3, 3, 3, 3, 3, 3], closed=True)
bridge_edge_loops(name='stand_1', profile_name=['loop_1_1', 'loop_2_1'], number_cuts=12, smoothness=1., profile_shape_factor=0.1, flip_normals=False)

# part_2: back
create_curve(name=['loop_1_2', 'loop_2_2'], control_points=[[[-0.26, -0.041, 0.723], [0.001, -0.041, 0.723], [0.261, -0.041, 0.723], [0.366, -0.041, 0.399], [0.366, -0.041, 0.152], [0.366, -0.041, -0.008], [0.158, -0.041, -0.192], [0.001, -0.041, -0.192], [-0.157, -0.041, -0.192], [-0.361, -0.041, -0.008], [-0.361, -0.041, 0.152], [-0.361, -0.041, 0.399]], [[-0.076, -0.569, 0.276], [0.001, -0.569, 0.276], [0.077, -0.569, 0.276], [0.109, -0.569, 0.179], [0.109, -0.569, 0.105], [0.109, -0.569, 0.064], [0.05, -0.569, 0.007], [0.001, -0.569, 0.007], [-0.049, -0.569, 0.007], [-0.109, -0.569, 0.064], [-0.109, -0.569, 0.105], [-0.109, -0.569, 0.179]]], handle_type=[3, 3, 3, 3, 3, 3, 3, 3], closed=True)
bridge_edge_loops(name='BridgeLoop_2_2', profile_name=['loop_1_2', 'loop_2_2'], number_cuts=13, smoothness=1., profile_shape_factor=0.11, interpolation='SURFACE', fill_caps='both')
create_curve(name=['loop_3_2', 'loop_4_2'], control_points=[[[0.24, -0.041, 0.152], [0.134, -0.253, 0.152], [0.026, -0.356, 0.152], [-0.022, -0.356, 0.152], [-0.127, -0.253, 0.152], [-0.23, -0.041, 0.152]], [[0.18, -0.041, -0.412], [0.099, -0.253, -0.412], [0.018, -0.356, -0.412], [-0.017, -0.356, -0.412], [-0.106, -0.253, -0.412], [-0.188, -0.041, -0.412]]], handle_type=[1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1], closed=True)
corrective_smooth(name=['loop_3_2', 'loop_4_2'])
bridge_edge_loops(name='back_2', profile_name=['loop_3_2', 'loop_4_2'], number_cuts=8, flip_normals=True, fill_caps='end')
boolean_operation(name1='back_2', name2='BridgeLoop_2_2', operation='DIFFERENCE', solver_mode='EXACT')

# part_3: tube
create_curve(name=['loop_1_3', 'loop_2_3', 'loop_3_3'], control_points=[[[-0.158, -0.065, 0.358], [0.001, -0.065, 0.359], [0.159, -0.065, 0.36], [0.185, -0.069, 0.162], [0.186, -0.069, 0.044], [0.187, -0.069, -0.055], [0.097, -0.069, -0.127], [0.002, -0.069, -0.128], [-0.092, -0.069, -0.129], [-0.185, -0.069, -0.057], [-0.186, -0.069, 0.042], [-0.187, -0.069, 0.16]], [[-0.158, -0.061, 0.358], [0.001, -0.061, 0.359], [0.159, -0.061, 0.36], [0.185, -0.061, 0.162], [0.186, -0.061, 0.044], [0.187, -0.061, -0.055], [0.097, -0.061, -0.127], [0.002, -0.061, -0.128], [-0.092, -0.061, -0.129], [-0.185, -0.061, -0.057], [-0.186, -0.061, 0.042], [-0.187, -0.061, 0.16]], [[-0.05, -0.327, 0.104], [0.001, -0.327, 0.104], [0.052, -0.327, 0.105], [0.064, -0.327, 0.05], [0.064, -0.327, 0.02], [0.065, -0.327, -0.01], [0.04, -0.327, -0.032], [0.002, -0.327, -0.032], [-0.037, -0.327, -0.033], [-0.067, -0.327, -0.011], [-0.067, -0.327, 0.019], [-0.067, -0.327, 0.049]]], handle_type=[3, 3, 3, 3, 3, 3, 3, 3], closed=True)
bridge_edge_loops(name=['edge_1_3', 'edge_2_3'], profile_name=[['loop_1_3', 'loop_2_3'], ['loop_1_3', 'loop_3_3']], number_cuts=[0, 13], smoothness=1., profile_shape_factor=[0, 0.1], interpolation='SURFACE', flip_normals=False)
join_obj(name='tube_3', seq_name=['edge_1_3', 'edge_2_3'], weld_threshold=1e-4)
solidify(name='tube_3', thickness=0.05, offset=1)
bevel(name='tube_3', width=0.07, segments=5)

# part_4: seat
create_curve(name='loop_1_4', control_points=[[0.174, -0.061, 0.422], [0.001, -0.061, 0.422], [-0.172, -0.061, 0.422], [-0.244, -0.061, 0.234], [-0.244, -0.061, 0.052], [-0.244, -0.061, -0.12], [-0.145, -0.061, -0.174], [-0.145, -0.061, -0.24], [0.15, -0.061, -0.24], [0.15, -0.061, -0.174], [0.244, -0.061, -0.12], [0.244, -0.061, 0.052], [0.244, -0.061, 0.234]], handle_type=[3, 3, 3, 3, 0, 1,1, 1, 1, 1, 1, 0, 3, 3], closed=True)
create_curve(name='loop_2_4', control_points=[[0.133, -0.061, 0.336], [0.001, -0.061, 0.336], [-0.131, -0.061, 0.336], [-0.185, -0.061, 0.188], [-0.185, -0.061, 0.052], [-0.185, -0.061, -0.08], [-0.095, -0.061, -0.114], [0.001, -0.061, -0.13], [0.097, -0.061, -0.114], [0.185, -0.061, -0.08], [0.185, -0.061, 0.052], [0.185, -0.061, 0.188]], handle_type=[3, 3, 3, 3, 3, 3, 3, 3], closed=True)
bridge_edge_loops(name='seat_4', profile_name=['loop_1_4', 'loop_2_4'], fill_caps='none', number_cuts=0)
solidify(name='seat_4', thickness=0.02)

# part_5: tank
create_primitive(name='tank_5', primitive_type='cube', location=[0.0, 0.07, -0.33], scale=[0.19, 0.15, 0.08], rotation=[0.0, 0.0, 0.0, 1.0])
bevel(name='tank_5', width=0.28, segments=2)

# part_6: cover
create_curve(name='loop_1_6', control_points=[[-0.186, 0.49, 0.131], [0.001, 0.49, 0.131], [0.187, 0.49, 0.131], [0.245, 0.34, 0.032], [0.245, 0.177, -0.081], [0.245, 0.047, -0.17], [0.15, -0.008, -0.213], [0.15, -0.053, -0.246], [-0.145, -0.053, -0.246], [-0.145, -0.008, -0.213], [-0.244, 0.047, -0.17], [-0.244, 0.177, -0.081], [-0.244, 0.34, 0.032]], handle_type=[3, 3, 3, 3, 0, 1,1, 1, 1, 1, 1, 0, 3, 3], closed=True)
create_curve(name='loop_2_6', control_points=[[-0.186, 0.502, 0.121], [0.001, 0.502, 0.121], [0.187, 0.502, 0.121], [0.245, 0.352, 0.021], [0.245, 0.189, -0.099], [0.245, 0.059, -0.188], [0.15, -0.001, -0.231], [0.15, -0.046, -0.264], [-0.145, -0.046, -0.264], [-0.145, -0.001, -0.231], [-0.244, 0.059, -0.188], [-0.244, 0.189, -0.099], [-0.244, 0.352, 0.021]], handle_type=[3, 3, 3, 3, 0, 1,1, 1, 1, 1, 1, 0, 3, 3], closed=True)
bridge_edge_loops(name='cover_6', profile_name=['loop_1_6', 'loop_2_6'], fill_caps='both', number_cuts=0)

# part_7: cap
create_primitive(name='cap_7', primitive_type='cube', location=[0.0, 0.21, -0.33], scale=[0.19, 0.08, 0.02], rotation=[0.0, 0.0, 0.71, 0.71])

# part_8: button
create_primitive(name='button_8', primitive_type='cylinder', location=[0.0, 0.23, -0.33], scale=[0.02, 0.02, 0.01], rotation=[0.45, 0.45, 0.54, -0.55])